language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install --yes gcc python3-dev libsqlcipher-dev
  - pip install -U pip
  - pip install pycodestyle codecov
  - python3 setup.py install
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - coverage run --source=. -m pytest
  - coverage report -m
after_success:
  - codecov
